"""Pydantic schemas for API models."""

from .deployment import (
    BackupConfig,
    DeploymentListResponse,
    DeploymentLogs,
    DeploymentMetrics,
    DeploymentRequest,
    DeploymentResponse,
    DeploymentSpec,
    DeploymentStatus,
    DeploymentUpdateRequest,
    MonitoringConfig,
    NetworkingConfig,
    ResourceRequirements,
    ScalingConfig,
)
from .error import (
    ErrorAnalysis,
    ErrorDiagnosisRequest,
    ErrorDiagnosisResponse,
    ImmediateAction,
    MonitoringRecommendation,
    RootCauseFix,
)
from .iac import (
    CostEstimate,
    GeneratedResource,
    IaCFormat,
    IaCGenerationRequest,
    IaCGenerationResponse,
    IaCGenerationResult,
    IaCProvider,
    IaCValidationRequest,
    IaCValidationResponse,
    IaCValidationResult,
    ValidationIssue,
    ValidationSeverity,
)
from .llm import LLMProviderStatus, LLMRequest, LLMResponse
from .requirement import (
    RequirementAnalysisRequest,
    RequirementAnalysisResponse,
    RequirementRefinementRequest,
)
from .template import (
    Template,
    TemplateCategory,
    TemplateListResponse,
    TemplateParameter,
    TemplateRequest,
    TemplateResource,
    TemplateResponse,
    TemplateStatus,
    TemplateUsageStats,
    TemplateValidation,
    TemplateValidationRequest,
    TemplateValidationResponse,
)

__all__ = [
    # Deployment schemas
    "DeploymentRequest",
    "DeploymentResponse",
    "DeploymentSpec",
    "DeploymentStatus",
    "DeploymentUpdateRequest",
    "DeploymentListResponse",
    "DeploymentLogs",
    "DeploymentMetrics",
    "ResourceRequirements",
    "ScalingConfig",
    "NetworkingConfig",
    "MonitoringConfig",
    "BackupConfig",
    # Template schemas
    "Template",
    "TemplateCategory",
    "TemplateListResponse",
    "TemplateParameter",
    "TemplateRequest",
    "TemplateResource",
    "TemplateResponse",
    "TemplateStatus",
    "TemplateUsageStats",
    "TemplateValidation",
    "TemplateValidationRequest",
    "TemplateValidationResponse",
    # Requirement schemas
    "RequirementAnalysisRequest",
    "RequirementAnalysisResponse",
    "RequirementRefinementRequest",
    # Error schemas
    "ErrorDiagnosisRequest",
    "ErrorDiagnosisResponse",
    "ErrorAnalysis",
    "ImmediateAction",
    "RootCauseFix",
    "MonitoringRecommendation",
    # LLM schemas
    "LLMProviderStatus",
    "LLMRequest",
    "LLMResponse",
    # IaC schemas
    "IaCProvider",
    "IaCFormat",
    "IaCGenerationRequest",
    "IaCGenerationResponse",
    "IaCGenerationResult",
    "IaCValidationRequest",
    "IaCValidationResponse",
    "IaCValidationResult",
    "ValidationIssue",
    "ValidationSeverity",
    "GeneratedResource",
    "CostEstimate",
]
